# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  release: 
    types: [created, gpublished]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9
      - name: Install Packages
        run: |
         python3 -m pip install build
         python3 -m pip install twine
      - name: Build Artifact
        run: |
         python3 -m build
      
      - name: Upload Artifact to PyPI
        env:
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
          TWINE_USERNAME: __token__
        run: |
          python3 -m twine upload dist/*
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          # Artifact name
          name: "discord-ui"
          # A file, directory or wildcard pattern that describes what to upload
          path: "dist/*"
          
      - name: Download Artifact
        uses: actions/download-artifact@v2.0.10
        with:
          path: dist/
#      - name: pypi-publish
#        uses: pypa/gh-action-pypi-publish@v1.4.2
#        with:
#          user: __token__
#          password: ${{ secrets.PYPI_TEST_TOKEN }}
#          repository_url: https://test.pypi.org/project/discord-ui/
